llvmdev:  # [not win]
  - 11  # [not win]
  - 12  # [not win]
llvm:  # [not win]
  - 11  # [not win]
  - 12  # [not win]
zip_keys:  # [not win]
  - llvmdev  # [not win]
  - llvm  # [not win]
c_compiler:                    # [win]
- vs2019                       # [win]
cxx_compiler:                  # [win]
- vs2019                       # [win]
