llvmdev:
  - 15
  - 16
  - 17
  - 18
  - 19
llvm:
  - 15
  - 16
  - 17
  - 18
  - 19
zip_keys:
  - llvmdev
  - llvm
# NOTE: need GCC 11 on ppc64 due to this Boost bug:
# https://github.com/boostorg/multiprecision/issues/419
# NOTE: pin clang to version 16 on OSX x86_64
# for the time being, due to what looks like a clang-19 bug.
c_compiler_version:        # [ppc64le or (osx and x86_64)]
  - 11                     # [ppc64le]
  - 18                     # [osx and x86_64]
cxx_compiler_version:      # [ppc64le or (osx and x86_64)]
  - 11                     # [ppc64le]
  - 18                     # [osx and x86_64]
