llvmdev:
  - 11  # [not win]
  - 12
  - 13
  - 14
  - 15  # [not win]
llvm:
  - 11  # [not win]
  - 12
  - 13
  - 14
  - 15  # [not win]
zip_keys:
  - llvmdev
  - llvm
c_compiler:                    # [win]
- vs2019                       # [win]
cxx_compiler:                  # [win]
- vs2019                       # [win]
