llvmdev:
  - 11
  - 12
llvm:
  - 11
  - 12
zip_keys:
  - llvmdev
  - llvm
c_compiler:                    # [win]
- vs2019                       # [win]
cxx_compiler:                  # [win]
- vs2019                       # [win]
