llvmdev:
  - 11  # [not win]
  - 12
  - 13
  - 14
  - 15  # [not win]
llvm:
  - 11  # [not win]
  - 12
  - 13
  - 14
  - 15  # [not win]
zip_keys:
  - llvmdev
  - llvm
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
