llvmdev:
  - 14
  - 15
  - 16
  - 17
  - 18
llvm:
  - 14
  - 15
  - 16
  - 17
  - 18
zip_keys:
  - llvmdev
  - llvm
# NOTE: need GCC 11 on ppc64 due to this Boost bug:
# https://github.com/boostorg/multiprecision/issues/419
c_compiler_version:        # [ppc64le]
  - 11                     # [ppc64le]
cxx_compiler_version:      # [ppc64le]
  - 11                     # [ppc64le]
