{% set version = "0.19.0" %}

package:
  name: heyoka
  version: {{ version }}

source:
  url: https://github.com/bluescarni/heyoka/archive/v{{ version }}.tar.gz
  sha256: 7a7634379233be778fd6b15090df287787cc429314ec521d0336cdc1ae26642a

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.8.0
    - make       # [unix]

outputs:
  - name: heyoka
    requirements:
      host:
        - llvmdev
        - llvm
        - boost-cpp
        - fmt
        - spdlog
        - tbb-devel
        - sleef         # [not osx]
        - xtensor       # [not osx]
        - xtensor-blas  # [not osx]
        - blas          # [not osx]
        - blas-devel    # [not osx]
        - mppp >=0.23   # [linux and (x86 or ppc64le)]
        - zlib          # [win]
        - libzlib       # [win]
      run:
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    build:
      run_exports:
        # SO name changes at minor rev bumps.
        - {{ pin_subpackage('heyoka', max_pin='x.x') }}
    files:
      - lib/libheyoka*{{ SHLIB_EXT }}   # [not win]
      - lib/libheyoka.so.*              # [linux]
      - lib/libheyoka.*.dylib           # [osx]
      - Library/bin/heyoka.dll          # [win]
      - include/heyoka                  # [not win]
      - lib/cmake/heyoka                # [not win]
      - Library/include/heyoka          # [win]
      - Library/lib/heyoka.lib          # [win]
      - Library/lib/cmake/heyoka        # [win]
    test:
      commands:
        - test -f $PREFIX/include/heyoka/heyoka.hpp               # [unix]
        - if not exist %PREFIX%\\Library\\include\\heyoka\\heyoka.hpp exit 1   # [win]
  - name: heyoka-llvm-{{ llvmdev }}
    requirements:
      host:
        - llvmdev
        - llvm
        - boost-cpp
        - fmt
        - spdlog
        - tbb-devel
        - sleef         # [not osx]
        - xtensor       # [not osx]
        - xtensor-blas  # [not osx]
        - blas          # [not osx]
        - blas-devel    # [not osx]
        - mppp >=0.23   # [linux and (x86 or ppc64le)]
        - zlib          # [win]
        - libzlib       # [win]
        - {{ pin_subpackage('heyoka', exact=True) }}
      run:
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
        - {{ pin_subpackage('heyoka', exact=True) }}
    build:
      run_exports:
        - {{ pin_subpackage('heyoka', exact=True) }}
    test:
      commands:
        - test true               # [unix]

about:
  home: https://bluescarni.github.io/heyoka/
  license: MPL-2.0
  license_file: COPYING
  summary: A C++ library for ODE integration via Taylor's method, based on LLVM

extra:
  recipe-maintainers:
    - bluescarni
