{% set version = "3.2.0" %}

package:
  name: heyoka
  version: {{ version }}

source:
  url: https://github.com/bluescarni/heyoka/archive/v{{ version }}.tar.gz
  sha256: 37db24fbaf0e65d740ffb20f76ac1c8ab9fbd6893dc87dfd483c965b71dbf465

build:
  number: 0
  ignore_run_exports_from:
    # NOTE: on most platforms, except
    # PPC64, we are forcing static linking
    # to LLVM in a desperate attempt to hide
    # LLVM symbols so that heyoka can coexist
    # (maybe) with other libraries linking to
    # different LLVM versions. On the other hand,
    # the conda packages for llvm/llvmdev inject
    # (on some platforms at least) a run_export()
    # dependency under the assumption
    # that dynamic linking is being used. We want to
    # avoid that, as the whole point is to hide
    # the presence of LLVM as much as possible.
    - llvmdev  # [not ppc64le]
    - llvm     # [not ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.18.0
    - make       # [unix]

outputs:
  - name: heyoka
    requirements:
      host:
        - llvmdev
        - llvm
        - libboost-devel
        # NOTE: this one is needed only
        # on some platforms and LLVM versions.
        # Just leave it everywhere even if
        # it will result in some overlinking.
        - zstd
        - fmt
        - spdlog
        - tbb-devel
        - sleef
        - gmp           # [unix]
        - mpir          # [win]
        - mpfr
        - xtensor       # [not osx]
        - xtensor-blas  # [not osx]
        - blas          # [not osx]
        - blas-devel    # [not osx]
        - mppp >=0.27
        - zlib          # [not ppc64le]
      run:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    build:
      run_exports:
        # SO name changes at minor rev bumps.
        - {{ pin_subpackage('heyoka', max_pin='x.x') }}
    files:
      - lib/libheyoka*{{ SHLIB_EXT }}   # [not win]
      - lib/libheyoka.so.*              # [linux]
      - lib/libheyoka.*.dylib           # [osx]
      - Library/bin/heyoka.dll          # [win]
      - include/heyoka                  # [not win]
      - lib/cmake/heyoka                # [not win]
      - Library/include/heyoka          # [win]
      - Library/lib/heyoka.lib          # [win]
      - Library/lib/cmake/heyoka        # [win]
    test:
      commands:
        - test -f $PREFIX/include/heyoka/heyoka.hpp               # [unix]
        - if not exist %PREFIX%\\Library\\include\\heyoka\\heyoka.hpp exit 1   # [win]
  - name: heyoka-llvm-{{ llvmdev }}
    requirements:
      host:
        - llvmdev
        - llvm
        - libboost-devel
        - zstd
        - fmt
        - spdlog
        - tbb-devel
        - sleef
        - gmp           # [unix]
        - mpir          # [win]
        - mpfr
        - xtensor       # [not osx]
        - xtensor-blas  # [not osx]
        - blas          # [not osx]
        - blas-devel    # [not osx]
        - mppp >=0.27
        - zlib          # [not ppc64le]
        - {{ pin_subpackage('heyoka', exact=True) }}
      run:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
        - {{ pin_subpackage('heyoka', exact=True) }}
    build:
      run_exports:
        - {{ pin_subpackage('heyoka', exact=True) }}
    test:
      commands:
        - test true               # [unix]

about:
  home: https://bluescarni.github.io/heyoka/
  license: MPL-2.0
  license_file: COPYING
  summary: A C++ library for ODE integration via Taylor's method, based on LLVM

extra:
  recipe-maintainers:
    - bluescarni
