{% set version = "0.16.0" %}

package:
  name: heyoka
  version: {{ version }}

source:
  url: https://github.com/bluescarni/heyoka/archive/v{{ version }}.tar.gz
  sha256: b58ac688d2cf7d6b67b0ec1adcda41568a87d98dfaae840acdd1b21c4eb3ee14

build:
  number: 0
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('heyoka', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make       # [unix]

  host:
    - llvmdev
    - llvm
    - boost-cpp
    - fmt
    - spdlog
    - sleef
    - xtensor
    - xtensor-blas
    - blas
    - blas-devel
    - tbb-devel
    - mppp  # [linux and (x86 or ppc64le)]

  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/include/heyoka/heyoka.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\heyoka\\heyoka.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/heyoka/
  license: MPL-2.0
  license_file: COPYING
  summary: A C++ library for ODE integration via Taylor's method, based on LLVM

extra:
  recipe-maintainers:
    - bluescarni
