{% set version = "0.15.0" %}

package:
  name: heyoka-split
  version: {{ version }}

source:
  url: https://github.com/bluescarni/heyoka/archive/v{{ version }}.tar.gz
  sha256: 5096a5592768938b3553d9d37827c3aaf993fd6ef8065e577b47758ed841e17b

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake <3.20
    - clang      # [win]
    - ninja      # [win]
    - make       # [unix]

outputs:
  - name: heyoka
    build:
      run_exports:
        # SO name changes at minor rev bumps.
        - {{ pin_subpackage('heyoka', max_pin='x.x') }}

    requirements:
      host:
        - llvmdev
        - llvm
        - boost-cpp
        - fmt
        - spdlog
        - sleef
        - xtensor
        - xtensor-blas
        - blas
        - blas-devel
        - tbb-devel
        - mppp  # [linux and (x86 or ppc64le)]

      run:
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}

    test:
      commands:
        - test -f $PREFIX/include/heyoka/heyoka.hpp               # [unix]
        - if not exist %PREFIX%\\Library\\include\\heyoka\\heyoka.hpp exit 1   # [win]

  - name: heyoka-llvm-{{ llvmdev }}
    requirements:
      host:
        - {{ pin_subpackage('heyoka', exact=True) }}
      run:
        - {{ pin_subpackage('heyoka', exact=True) }}
    test:
      commands:
        - test true               # [unix]

about:
  home: https://bluescarni.github.io/heyoka/
  license: MPL-2.0
  license_file: COPYING
  summary: A C++ library for ODE integration via Taylor's method, based on LLVM

extra:
  recipe-maintainers:
    - bluescarni
